name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - name: Build binary for macOS
        run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ip-update

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ip-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
